[package]
name = "aoc2022-rs"
version = "0.1.0"
authors = ["root"]
edition = "2018"
license-file = "LICENSE"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
serde = "1.0.125"
serde_json = "1.0.64"
cmake = "= 0.1.45"
